### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by 1397981186** [sunshaozong111/NS3-with-LEO#1]
校友唉，我最近在看SNS3相关的东西，不知道你现在还在做相关的研究吗，如果能交流一下是最好的。q1397981186

**Comment by sunshaozong111** [comment]
已经毕业，这方向太坑了



发自我的iPhone


------------------ Original ------------------
From: qq1397981186 ***@***.***&gt;
Date: Wed,Jul 21,2021 4:36 PM
To: sunshaozong111/NS3-with-LEO ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [sunshaozong111/NS3-with-LEO] communication (#1)





 
校友唉，我最近在看SNS3相关的东西，不知道你现在还在做相关的研究吗，如果能交流一下是最好的。q1397981186

**Comment by zbh888** [comment]
卫星快坑死我了 @sunshaozong111 @1397981186 兄弟们看过sns3吗
